// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlgen

import (
	"time"
)

type Address struct {
	ID          int64
	IsReserved  bool
	IsV6        bool
	HostID      int64
	OwnerUserID *int64
	Description *string
	DesyncedAt  time.Time
}

type User struct {
	ID            int64
	Name          string
	IsAdmin       bool
	IsBanned      bool
	Fare          string
	PrivateKey    string
	PublicKey     string
	AddressCount  int64
	MaxAddresses  int64
	PaidByTime    *time.Time
	TokenIssuedAt *time.Time
	LastSeenAt    *time.Time
}

type WgNetConfig struct {
	ID    int64
	V6Net string
	V4Net string
}
